import { ClerkProvider } from '@clerk/nextjs';
import { type AppType } from 'next/app';

import { api } from 'y/utils/api';

import 'y/styles/globals.css';
import { Toaster } from 'react-hot-toast';
import Head from 'next/head';

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <ClerkProvider {...pageProps}>
      <Head>
        <title>Tweemoji</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster position="bottom-center" />
      <Component {...pageProps} />
    </ClerkProvider>
  );
};

export default api.withTRPC(MyApp);
